Feature/process
aakb/kontrolgruppen pull request #1
Opened 2019-03-27 14:29 UTC by tuj

* Added process entity migrations
* Moved code out of App and into separate bundle: https://github.com/aakb/kontrolgruppen-core-bundle
* Added development setup and updated readme.

2019-03-27 16:14 UTC, rimi-itk requested changes

2019-03-27 16:14 UTC, rimi-itk commented on webpack.config.js
> +    .addEntry('core', './vendor/kontrolgruppen/core-bundle/assets/js/app.js')
I don't like the reference to `vendor` here. Shouldn't the core-bundle provide assets so we don't have to do anything unless we want to change some assets in this project?

2019-03-27 16:14 UTC, rimi-itk commented on scripts/install.sh
> +mkdir $dir/packages/kontrolgruppen
One-liner: `mkdir -p $dir/packages/kontrolgruppen`

2019-03-27 16:14 UTC, rimi-itk commented on scripts/develop.sh
> +bin/console assets:install --symlink --relative
This is already done in https://github.com/aakb/kontrolgruppen/blob/develop/composer.json#L68

2019-03-27 16:14 UTC, rimi-itk commented on scripts/develop.sh
> +#!/usr/bin/env bash
I think we should move the develop(ment) scripts in to `scripts/develop` to make it clear that they're only used for development. Then we can at some point add general install/update scripts, say, in the `scripts` folder.

2019-03-27 16:14 UTC, rimi-itk commented on README.md
> +## Setup for development
Maybe we should move this into a `README.develop.md` (or something like that) to keep `README.md` clean and only contain information needed for getting the project up and running.

2019-03-27 16:14 UTC, rimi-itk commented on README.md
> +/scripts/install.sh
Should be `./scripts/install.sh`.

2019-03-27 16:14 UTC, rimi-itk commented on README.md
> +/scripts/develop.sh
Should be `./scripts/develop.sh`.

2019-03-27 16:14 UTC, rimi-itk commented on README.md
> +Should be required in the `kontrolgruppen/core-bundle` bundle instead.
Well, it depends on if the bundles are generally neede or only needed in this project …

2019-03-27 16:14 UTC, rimi-itk commented on scripts/develop.sh
> +bin/console assets:install --symlink --relative
After running `./scripts/develop.sh`:

```sh
$ git status
…
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	assets/
	src/Repository/
	templates/base.html.twig
```
Can we prevent this?

2019-03-27 16:18 UTC, rimi-itk commented on composer.json
> +        "kontrolgruppen/core-bundle": "dev-develop",
This should probably be `…: "^1.0"` …

2019-03-27 16:22 UTC, rimi-itk commented on scripts/develop.sh
> +    done
Are we missing `composer require $vendor/$package:dev-develop` here? We want to require the `develop` branch from the packages, right?

2019-03-28 06:15 UTC, tuj commented on webpack.config.js
> +    .addEntry('core', './vendor/kontrolgruppen/core-bundle/assets/js/app.js')
This is definitely a problem area with the setup.
I have not been able to fix the webpack setup yet.
I'll add a comment to remember to fix it.

2019-03-28 06:29 UTC, tuj commented on README.md
> +Should be required in the `kontrolgruppen/core-bundle` bundle instead.
True. I'll remove the section.

2019-03-28 06:31 UTC, tuj commented on composer.json
> +        "kontrolgruppen/core-bundle": "dev-develop",
I will do that when there is a 1.0.0 version of the bundle

2019-03-28 06:31 UTC, tuj commented on scripts/develop.sh
> +    done
Yes

2019-03-28 06:33 UTC, tuj commented on README.md
> +## Setup for development
Done

2019-03-28 06:33 UTC, tuj commented on README.md
> +/scripts/install.sh
Done

2019-03-28 06:33 UTC, tuj commented on README.md
> +/scripts/develop.sh
Done

2019-03-28 06:33 UTC, tuj commented on scripts/develop.sh
> +#!/usr/bin/env bash
Done

2019-03-28 06:33 UTC, tuj commented on scripts/develop.sh
> +bin/console assets:install --symlink --relative
Yes

2019-03-28 06:33 UTC, tuj commented on scripts/install.sh
> +mkdir $dir/packages/kontrolgruppen
Done

2019-03-28 06:57 UTC, tuj commented on composer.json
> +        "kontrolgruppen/core-bundle": "dev-develop",
Changed to dev-master until a tag i ready, which will be changed to dev-develop by the develop.sh script.

2019-04-01 10:13 UTC, tuj commented on webpack.config.js
> +    .addEntry('core', './vendor/kontrolgruppen/core-bundle/assets/js/app.js')
Removed from project.
Webpack build setup added to core-bundle

2019-04-01 10:16 UTC, merged