Feature/remove submodule
aakb/kontrolgruppen pull request #53
Opened 2019-10-01 11:29 UTC by lats1

2019-10-01 13:52 UTC, rimi-itk requested changes
Looks good. A few comments have been added.

2019-10-01 13:52 UTC, rimi-itk commented on README-develop.md
> +```json
I think we should show console commands for making these changes:

```sh
composer config repositories.kontrolgruppen/core-bundle path bundles/core-bundle
composer require 'kontrolgruppen/core-bundle:dev-develop'
```
(symlinking is the default if possible, cf. https://getcomposer.org/doc/05-repositories.md#path)

Maybe we should even remove the `json` snippet …

2019-10-01 13:52 UTC, rimi-itk commented on README.md
> +
Maybe add something like

```sh
composer config repositories.kontrolgruppen/core-bundle vcs git@github.com:aakb/kontrolgruppen-core-bundle.git
```
(do we also need `composer require 'kontrolgruppen/core-bundle:«some branch name»'` here?)

and/or something like

> Run `git checkout --patch composer.json` to revert your develop changes to `composer.json`.

2019-10-01 13:52 UTC, rimi-itk commented on package.json
> +        "check-coding-standards-stylelint": "stylelint --config=.stylelintrc.js 'vendor/kontrolgruppen/core-bundle/Resources/assets/**/*.scss'",
I think, personally, that this should be moved to the `core-bundle`'s own `package.json`, but we'll leave it like this for now.

2019-10-02 07:17 UTC, tuj requested changes

2019-10-02 07:17 UTC, tuj commented on README-develop.md
> +Add core-bundle to the project:
Please add comment about not committing composer.json after this change has been made.

2019-10-03 08:37 UTC, rimi-itk approved these changes

2019-10-03 08:37 UTC, merged